# Generated by Django 3.0.7 on 2020-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='sno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
