# Generated by Django 3.0.7 on 2020-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200623_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
