# Generated by Django 3.0.7 on 2020-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200623_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
