# Generated by Django 3.0.7 on 2020-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200623_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('content', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
