# Generated by Django 3.0.7 on 2020-06-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
